version: 2

project_name: usbec

builds:
  - id: usbec
    binary: usbec
    main: .
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - PKG_CONFIG=aarch64-linux-gnu-pkg-config
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: usbec
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE
      - usbec.toml
      - hotplug/LICENSE.txt

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  prerelease: auto
